package NotePadApp;


/**
* NotePadApp/NotePadOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotePad.idl
* 26 но€бр€ 2019 г. 21:52:39 MSK
*/

public interface NotePadOperations 
{
  boolean addNote (String a, int b);
  void addNullNote ();
  boolean showNotes ();
  boolean deleteNote (int b);
  void shutdown ();
} // interface NotePadOperations
